# Generated by Django 4.0.10 on 2024-05-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_id_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_add_review', 'Can add review')]},
        ),
    ]
