# Generated by Django 4.0.10 on 2024-05-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
